### ISSUE TITLE
Focuses the second item in the list, after navigating from the fixed menu

### ISSUE THREAD

**Issue by VIKSUA** [NoriginMedia/react-spatial-navigation#106]
**Describe the bug**
On the left side a fixed vertical menu on the right a horizontal list.
If the menu has hasFocusedChild=true its width is increased.
When navigating to the right, the second list item is focused.

**To Reproduce**
1. Navigate to the menu from the first item in the list
2. Click on 'right'
3. Second element of the list is focused

**Expected behavior**
After right click the first element of the list should be focused

**Screenshots**
https://prnt.sc/1qac4h5
https://prnt.sc/1qac743

**Additional context**
Does not matter whether the menu overlaps or shifts

**Comment by asgvard** [comment]
Hi. This is a quite common problem when there are overlapping elements on the screen. If the menu is expanded - when you click Right - it will calculate the coordinate based on the expanded menu - so the next target is the 2nd item. We solve this by having the menu to be outside of the screen (by doing absolute position "-menuWidth"), and then translating it back for the same amount with "translateX(menuWidth)". This makes it to have the "real" coordinate to be far away to the left, but to appear visually as though as it is overlapping the page. Hope it helps. It's hard to say in more detail without knowing the full DOM structure.

**Comment by predikament** [comment]
Closing issue due to no further activity or input from @Viktorsua since the response by @asgvard in August.
