### ISSUE TITLE
Understanding of roadmap for library

### ISSUE THREAD

**Issue by stuartflanagan** [NoriginMedia/react-spatial-navigation#111]
Just asking to get an understanding of the plans for this library. Removal of Re-compose and a move to hooks while removing reliance on `ReactDOM.findDOMNode` which will not be supported in React18.

Is there a version we can create that is not as concerned about backwards compatibility?

**Comment by predikament** [comment]
Hello @stuartflanagan 👋

Firstly I'd like to say thanks for being one of the repository's most active contributors outside of our organization.

As to your question - We are currently in the process of planning the roadmap ahead for this library and want to address most of the feedback we've received, like the usage of re-compose, `findDOMNode`, rewriting to hooks, etc.

We will update the README to highlight this and what the future has in hold for the library as a whole once the new architecture and general plan has been solidified. Hoping this will happen in the next few weeks, if all goes to schedule.

**Comment by stuartflanagan** [comment]
Thank you for this response @predikament.

Please let us know if you have any advance branches or PRs we can help review.

**Comment by stuartflanagan** [comment]
Hello and Happy New Year @predikament 
We had some issues yesterday with our builds due to the new GitHub security policy testing that are coming into effect March 15.

They seem to be as a result of re-compose and reliance on ua-parser. Just wondering if you were aware as this may present some issues with application builds from March 15.

**Comment by predikament** [comment]
> Hello and Happy New Year @predikament We had some issues yesterday with our builds due to the new GitHub security policy testing that are coming into effect March 15.
> 
> They seem to be as a result of re-compose and reliance on ua-parser. Just wondering if you were aware as this may present some issues with application builds from March 15.

👋 Hello, thanks and a Happy New Year to you as well, @stuartflanagan.

I have raised this internally, since this basically infers a deadline for us in terms of having to reach our future roadmap goals. 

Thank you for the feedback. It is appreciated. I will do my best to get back to you as soon as I have any updates to share in regards to this. Sorry I can't be more concrete as of now - We have a lot of wheels turning internally at the moment. 😅

**Comment by asgvard** [comment]
Hello! Here is the new version of this library that is migrated to hooks: https://github.com/NoriginMedia/Norigin-Spatial-Navigation
