### ISSUE TITLE
display none control

### ISSUE THREAD

**Issue by toneyavuz** [NoriginMedia/react-spatial-navigation#122]
I used the react-navigation stack for my application and the package doesn't remove the old pages, just changes the display none.
I recorded a video.

I have no problem when I move between the active page buttons but sometimes my focus is lost on the active screen and focus on hidden pages.

<img width="515" alt="Screen Shot 2022-04-29 at 8 18 57 PM" src="https://user-images.githubusercontent.com/14276250/165992644-e5031797-e855-4c07-a6a3-d038ee77cf04.png">

https://wetransfer.com/downloads/4b6a8eae305cd7fc60e0905e21a4941f20220429170949/3b82663c35e87e0ab11036fa9649968620220429171004/15e19d

**Comment by asgvard** [comment]
Hi!

Keep in mind that this library is no longer maintained.
However the good news is that your problem can be solved by this feature: https://github.com/NoriginMedia/react-spatial-navigation#blocknavigationout-boolean
If you set this to your Page component, it will block focus from going outside of it, i.e. to the hidden pages underneath.

**Comment by toneyavuz** [comment]
Thank you! @asgvard
