### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by burakkirkil** [NoriginMedia/react-spatial-navigation#30]
**Problem:**
I get a 'window is not defined' error when I try to use in SSR application with razzle framework because virtualDebugger is using 'window' object without checking it is exist or not.

Even I got an error without using virtual debugger.

**Solution:**
Adding basic 'window' check for SSR support.

**Comment by asgvard** [comment]
That's a valid point. Will add this as soon as we have time.

**Comment by cankahya** [comment]
I got the same issue, trying to implement your (very promising!) library within a Next.js app.
So +1 on this one. In the meantime I am trying to figure it out myself! Cheers
