### ISSUE TITLE
Create onFocusOut

### ISSUE THREAD

**Issue by JakubKubista** [NoriginMedia/react-spatial-navigation#33]
**Is your feature request related to a problem? Please describe.**
The library react-spatial-navigation contains onBecameFocused (which works as JS focus - https://developer.mozilla.org/en-US/docs/Web/API/Element/focus_event), but not onFocusOut (oposite). Or maybe better case onFocused, which would returns true/false.

**Describe the solution you'd like**
MDN has this functionality like this:
https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event

**Describe alternatives you've considered**
Currently we need to use a prop focused from child component A to send it to parent component B, if we want to use this focused property in another component C (included in component A).

**Comment by asgvard** [comment]
This is now implemented as `onBecameBlurred` in #59  (for naming convention we already had, which perhaps is not perfect :) ).
