### ISSUE TITLE
Need to add setFocusByDirection("left", "right", "top" or "bottom")

### ISSUE THREAD

**Issue by yarikleto** [NoriginMedia/react-spatial-navigation#34]
When I handle the wheel event, I need to move to the top or bottom (I won't use focus by keys).

We can use a `smartNavigate` method of the `SpatialNavigation` class.

```js
onKeyEvent(keyCode) {
    this.visualDebugger && this.visualDebugger.clear();

    const direction = findKey(this.getKeyMap(), (code) => keyCode === code);

    this.smartNavigate(direction); // We can use it
}
```

**Comment by salvan13** [comment]
Hi @alfimois 
Usually mouse wheel doesn't change focus on elements, not sure if we should add this. Can you explain your use case step by step?

**Comment by yarikleto** [comment]
Added by that PR https://github.com/NoriginMedia/react-spatial-navigation/pull/36

**Comment by salvan13** [comment]
Thanks! 
So basically you need a method for navigate in a certain direction programmatically. Right?

In this case I would call it `navigateTo(direction)` or `focusNext(direction)` instead of `smartNavigateByDirection(direction)` (since smartNavigate is not used in the public api).

what do you think @asgvard ?

**Comment by salvan13** [comment]
@alfimois also please when you open a pull request don't mix things: like refactoring + new feature.
Let's keep pull request minimal and focus on one thing.
Thanks!

**Comment by asgvard** [comment]
@salvan13 Perhaps `navigateByDirection` is a good name. Because "navigateTo" might mean "navigate to some place" instead of direction. Also "focusNext" might mean it focuses some component.
@alfimois I'll add some comments to PR in a minute

**Comment by yarikleto** [comment]
> Let's keep pull request minimal and focus on one thing.
@salvan13 OK, sry)

**Comment by yarikleto** [comment]
> Usually mouse wheel doesn't change focus on elements, not sure if we should add this. Can you explain your use case step by step?

Our TVs can change focusing by a wheel on the remote ;)

**Comment by yarikleto** [comment]
Added https://github.com/NoriginMedia/react-spatial-navigation/pull/36
