### ISSUE TITLE
Optimization of `getNextFocusKey` method

### ISSUE THREAD

**Issue by yarikleto** [NoriginMedia/react-spatial-navigation#40]
This method recursively finds a focusable child without his own focusable children.

If the `preferredChildFocusKey` and `lastFocusedChildKey` are "disabled", we need to select at least something.

```js
// getNextFocusKey method

/**
 * Otherwise, trying to focus something by coordinates
*/
  const sortedXChildren = sortBy(children, (child) => child.layout.left);
  const sortedYChildren = sortBy(sortedXChildren, (child) => child.layout.top);
  const {focusKey: childKey} = first(sortedYChildren);

  this.log('getNextFocusKey', 'childKey will be focused', childKey);

  return this.getNextFocusKey(childKey);
```

Here, we try to find a component closer to (x: 0, y: 0). It's `O(2n)`

```js
const [{focusKey: childKey}] = sortBy(
  children, ({layout}) => Math.abs(layout.left) + Math.abs(layout.top)
);
```
It's the same. `O(n)`.

Or we can just pick a first child. It's very fast :)
```js
const [{focusKey: childKey}] = children
```

**Comment by asgvard** [comment]
Although this is not a huge bottleneck, it looks like a nice optimisation with single `sortBy` way. Picking first child seems a bit random though. Could you submit a PR please?

**Comment by yarikleto** [comment]
Thank you for your answer. OK

**Comment by asgvard** [comment]
Merged, will be published soon :)

**Comment by yarikleto** [comment]
🥳
