### ISSUE TITLE
Error when Server Side Rendering

### ISSUE THREAD

**Issue by stuartflanagan** [NoriginMedia/react-spatial-navigation#94]
**Describe the bug**
Server Side Rendering and Static Builds fail with window is undefined

**To Reproduce**
Render Component that utilises `withFocusable` on an environment without the window object

**Expected behavior**
All operations that require `window` should not run and component should render on the server without issue.

**Screenshots**
<img width="1552" alt="Screen Shot 2021-06-26 at 10 00 27 pm" src="https://user-images.githubusercontent.com/811015/123512278-ec876980-d6c9-11eb-9740-29a3e18f876e.png">

**Additional context**
This issue was fixed

**Comment by asgvard** [comment]
Closing as fixed by #95, will be part of the next release on Monday 28th
